name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Install git-cliff
      run: |
        curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.10.0/git-cliff-linux-x86_64.tar.gz | tar xz
        sudo mv git-cliff /usr/local/bin/

    - name: Generate changelog
      run: git-cliff -o CHANGELOG.md

    - name: Build binaries
      run: |
        mkdir dist
        GOOS=linux GOARCH=amd64 go build -o dist/yiff-linux-amd64 ./cmd/cli
        GOOS=darwin GOARCH=amd64 go build -o dist/yiff-darwin-amd64 ./cmd/cli
        GOOS=windows GOARCH=amd64 go build -o dist/yiff-windows-amd64.exe ./cmd/cli

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
